### ISSUE TITLE
Ordered & Unordered lists error

### ISSUE THREAD

**Issue by mckey** [lahdekorpi/Wiky.php#1]
Wrong parsing of lists if first list item appears at first line of text.

**Comment by lahdekorpi** [comment]
Could You provide sample data, output and expected output?
Thanks!

**Comment by mckey** [comment]
![Hope this help](http://mckey.info/jing/2012-03-01_1333_001.png)

Thanks!

**Comment by lahdekorpi** [comment]
Ah, it's because line 47: "/[\n\r]*.+([\n|\r]*.+)+/",                 // First pass, finding all blocks
Only matches if there is [\n\r], I'll have to do some brain work to fix it so that nothing else breaks.

A quick hack would be to just add a new empty line :)

**Comment by mckey** [comment]
Great!

Thanks a lot for this class.

**Comment by mckey** [comment]
Yep, i know about adding empty line, but in my case this solution is not applicable.

**Comment by slevesque** [comment]
Did you tried this to solve the list error ?

line 47: "/[\n\r]?_.+([\n|\r]_.+)+/", // First pass, finding all blocks

**Comment by lahdekorpi** [comment]
Should now work, thanks to Sylvain Lévesque :)
