### ISSUE TITLE
Setting Wiki parameters for alignment

### ISSUE THREAD

**Issue by fabiocosta0305** [lahdekorpi/Wiky.php#4]
Hey

Any chance to set wiki symbols for alignment?

**Comment by lahdekorpi** [comment]
What kind of markup on the wiki side are you looking for?

**Comment by fabiocosta0305** [comment]
Thought on something more simple like

> right align
> < left align
> ^ centered

**Comment by lahdekorpi** [comment]
Those would most likely have problems as they might be used for common text.

What do other wiki-syntaxes use?
