### ISSUE TITLE
Does not parse headings

### ISSUE THREAD

**Issue by karmadice** [lahdekorpi/Wiky.php#5]
This is what I wrote 
== Heading ==

'''Bold'''
''Italic''
{{Test/sample}}

And this is what I got 

== Heading ==

Bold

Italic

{{Test/sample}}

If I want to Parse heading or subheading, I have to use them only once. ie. 

== This is sample H1 ==

It'll not parse heading if I write 

== This is sample H1 ==  ===This is sample H2===
It wont parse anything

OR

== This is sample H1 ==
=== This is sample H2 ===

It'll parse Subheading

**Comment by lahdekorpi** [comment]
I just tested with PHP 5.4.17:

```
== Heading ==

'''Bold'''
''Italic''
{{Test/sample}}


== This is sample H1 ==
=== This is sample H2 ===

```

Became 

```
<h1>Heading</h1>

<strong>Bold</strong><br/>
<em>Italic</em><br/>
{{Test/sample}}<br/>


<h1>This is sample H1</h1>
<h2>This is sample H2</h2>
```

As it should. What version of PHP are you using and have you done any modifications? Does the example howto.php work as it should?

== This is sample H1 == ===This is sample H2===
This won't be parsed by design, headers need to be on separate new lines.

**Comment by karmadice** [comment]
I am Using PHP 5.4 .I changed Some patterns and now its working fine.

This is my change in patterns 

"/====== (.+?) ======/m",
"/===== (.+?) =====/m",
"/==== (.+?) ====/m",
"/=== (.+?) ===/m",
"/== (.+?) ==/m",

Even if Headings are in same line it'll parse them but will render them in saperate lines  :(

**Comment by lahdekorpi** [comment]
Wait, do you mean the browser renders them in separate lines, or the code has <br>?

Can you post the outputted HTML?

h\* elements are rendered as "display: block" and go to "new lines" by default as they are 100% width.
If you want to change that, just add a CSS style of h1, h2, h3, h4, h5 { display: inline }
or "inline-block".
