### ISSUE TITLE
Can't parse wiki table?

### ISSUE THREAD

**Issue by takien** [lahdekorpi/Wiky.php#7]
Trying to parse wiki formatted table using this library
http://en.wikipedia.org/wiki/Help:Table

**Comment by lahdekorpi** [comment]
The list of supported syntax is here:
https://github.com/lahdekorpi/Wiky.php#supported-syntax

Currently the main goal is to replicate the functionality of this project: https://github.com/tanin47/wiky.js
but using regular expressions.
